#SPDX-License-Identifier: MIT-0
---
# handlers file for lighthouse-role
- name: Restart apache
  ansible.builtin.systemd:
    name: apache2
    state: restarted

- name: Reload nginx
  ansible.builtin.command: nginx -s reload
  register: my_output
  changed_when: my_output.rc != 0
